### ISSUE TITLE
Implement Error for CoseError

### ISSUE THREAD

**Issue by janosimas** [google/coset#60]
Is there any reason for `CoseError` not to implement `Error`?
This causes issues when working with other libraries, like `thiserror`

**Comment by daviddrysdale** [comment]
The original reason was because this crate is `#[no_std]`, and `Error` used to be `std`-only.  

AIUI `Error` has now [moved](https://github.com/rust-lang/project-error-handling/issues/3) into `core`, but I guess that would require a suitable MSRV to use.

In the meanwhile, I guess we could add a (non-default) `std` feature that adds an `Error` implementation.

**Comment by janosimas** [comment]
The `std` feature looks good to me

**Comment by daviddrysdale** [comment]
Fixed in #61
